import mongoose from "mongoose";

const followUpCodeSchema = new mongoose.Schema(
  {
    code:               { type: String, required: true, unique: true, index: true },
    roomId:             { type: String, required: true, index: true },
    sessionId:          { type: mongoose.Schema.Types.ObjectId, ref: "Session", default: null },
    studentFirebaseUid: { type: String, required: true },
    soulteeFirebaseUid: { type: String, required: true },

    // pending  = generated by soultee, not yet activated by student
    // active   = student activated, follow-up chat is unlocked
    // expired  = 7-day window has passed, chat relocked
    status: { type: String, enum: ["pending", "active", "expired"], default: "pending" },

    activatedAt: { type: Date, default: null },
    expiresAt:   { type: Date, default: null },
  },
  { timestamps: true }
);

followUpCodeSchema.index({ roomId: 1, status: 1 });
followUpCodeSchema.index({ expiresAt: 1, status: 1 });

export default mongoose.model("FollowUpCode", followUpCodeSchema);
