import mongoose from "mongoose";

const followUpOtpSchema = new mongoose.Schema(
  {
    otp:                { type: String, required: true, unique: true, index: true },
    roomId:             { type: String, required: true, index: true },
    sessionId:          { type: mongoose.Schema.Types.ObjectId, ref: "Session", default: null },
    studentFirebaseUid: { type: String, required: true },
    soulteeFirebaseUid: { type: String, required: true },

    // ACTIVE  = generated by soultee, waiting for student to enter
    // USED    = student activated, follow-up chat is unlocked (7-day window)
    // EXPIRED = 7-day window has passed, chat relocked
    status: { type: String, enum: ["ACTIVE", "USED", "EXPIRED"], default: "ACTIVE" },

    // Duration mirrors the original paid session (e.g. 10, 20, 30, 60 minutes)
    durationMinutes: { type: Number, default: 60 },

    activatedAt: { type: Date, default: null },
    expiresAt:   { type: Date, default: null }, // activatedAt + durationMinutes
  },
  { timestamps: true }
);

followUpOtpSchema.index({ roomId: 1, status: 1 });
followUpOtpSchema.index({ expiresAt: 1, status: 1 });

// Collection stored as "followupotps" in MongoDB
export default mongoose.model("FollowUpOtp", followUpOtpSchema, "followupotps");
